# Informations sur le site
title: M.A.S. Dupuis
author: Marc-Antoine Dupuis
description: >-
  Étudiant en science politique à l'Université Laval

# Thème utilisé
theme: minima

# Section spéciale pour les liens sociaux du thème Minima
minima:
  social_links:
    - platform: github
      user_url: "https://github.com/MADUP212"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/mdupuis212"
