title: M.A.S. Dupuis
author: Marc-Antoine Dupuis
description: >-
  Étudiant en science politique à l'Université Laval

theme: minima

# Réseaux sociaux compatibles Minima 2.x
github_username: MADUP212
linkedin_username: mdupuis212

navigation:
  - title: Parcours académique
    url: /parcours
  - title: CV
    url: /cv
  - title: Contact
    url: /contact
  - title: À Propos
    url: /about

