title: M.A.S. Dupuis
author: Marc-Antoine Dupuis
description: >-
  Étudiant en science politique à l'Université Laval

theme: minima

minima:
  social_links:
    - platform: github
      user_url: "https://github.com/MADUP212"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/mdupuis212"
