title: M.A.S. Dupuis
author: Marc-Antoine Dupuis
description: >-
  Étudiant en science politique à l'Université Laval

theme: minima

github_username: MADUP212
linkedin_username: mdupuis212

header_pages:
  - parcours.md
  - cv.md
  - contact.md
  - about.md

