[//]: # (Titre, Auteur laissé vide, Description)

title: M.A.S. Dupuis
author: 
description: >-
  Étudiant à la maîtrise en science politique à l'Université Laval, réserviste ARH dans les FAC. 

theme: minima

github_username: MADUP212
linkedin_username: mdupuis212
