[//]: # (Titre, Auteur laissé vide, Description)

title: M.A.S. Dupuis
author: 
description: >-
  Étudiant à la maîtrise en science politique à l'Université Laval, réserviste ARH dans les FAC. 

[//]: # (Thème du site web)
theme: minima

[//]: # (Lien pour les réseaux sociaux en bas de page) 
github_username: MADUP212
linkedin_username: mdupuis212

[//]: # (Sections) 
header_pages:
  - parcours.md
  - cv.md
  - contact.md
  - about.md

