title: M.A.S. Dupuis
author: Marc-Antoine Dupuis
description: >-
  Étudiant en science politique à l'Université Laval

theme: minima

# Réseaux sociaux compatibles Minima 2.x
github_username: MADUP212
linkedin_username: mdupuis212
